version: "3.9"
services:

  grafana:
    container_name: grafana
    image: grafana/grafana:7.5.6
    networks: [grafana_network]
    ports: [3000:3000]
    depends_on: [prometheus]
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.26.0
    networks: [grafana_network]
    ports: [9090:9090]
    volumes: 
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on: [node_exporter]

  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter:v1.1.2
    networks: [grafana_network]
    ports: [9100:9100]
    volumes: 
      - /:/host:ro
    restart: unless-stopped
    pid: host
    command:
      - '--path.rootfs=/host'

networks: 
  grafana_network:
    name: grafana_network
